### ISSUE TITLE
Move to the PackageKit organization?

### ISSUE THREAD

**Issue by Conan-Kudo** [PackageKit/PackageKit-Qt#38]
Some time ago, PackageKit itself moved to the PackageKit organization. Would you consider moving PackageKit-Qt to there too?

**Comment by aleixpol** [comment]
:+1:

**Comment by ximion** [comment]
Yes please! I don't have enough permissions on either the PackageKit organization or this repo to make the change, so, @hughsie? ;-)

**Comment by hughsie** [comment]
Done!

**Comment by ximion** [comment]
Nice, thank you!
